### ISSUE TITLE
Dimension Correction in Code

### ISSUE THREAD

**Issue by hamzakhalil798** [NickSwardh/YoloDotNet#1]
Thankyou so much for your work!
The code works fine just a small issue in your code in YoloDotNet/Extensions/ImageExtensions.cs line 33
var tensor = new DenseTensor<float>(new[] { inputBatchSize, inputChannels, height, width });

should be replaced with
var tensor = new DenseTensor<float>(new[] { inputBatchSize, inputChannels, width, height });

This fixes the dimension error (else dim error will occur for images not having same width and height).

**Comment by NickSwardh** [comment]
Thank you, awesome find! I've merged your pr. ;)
