### ISSUE TITLE
Support ImageSharp images as well as SkiaSharp ones

### ISSUE THREAD

**Issue by Webreaper** [NickSwardh/YoloDotNet#29]
Hi, I'm using this with images I've already loaded using ImageSharp. Is there any possibility you could provide overrides that'll work with both ImageSharp and SkiaSharp images? 

Alternatively, I'm going to try and convert: https://stackoverflow.com/questions/79085360/how-to-convert-an-imagesharp-image-to-a-skiasharp-skimage

**Comment by lwillems191** [comment]
I would say just convert your image. Keeps the library clean. And SkiaSharp is also faster.
If you got any questions about it. Let me know.

**Comment by Webreaper** [comment]
Yeah, it's figuring out how to convert the pixels.... 

SkiaSharp is only faster if I don't have to reload an image I already have in memory. ;) But yes, I use both.

**Comment by lwillems191** [comment]
```
byte[] buffer = new byte[width * height * 4];

// Copy the RGB values from the original image
for (int i = 0; i < width * height; i++)
{
    buffer[i * 4 + 0] = Marshal.ReadByte(image2d, i * 3 + 2); // Red
    buffer[i * 4 + 1] = Marshal.ReadByte(image2d, i * 3 + 1); // Green
    buffer[i * 4 + 2] = Marshal.ReadByte(image2d, i * 3 + 0); // Blue
    buffer[i * 4 + 3] = 255; // Alpha
}
return SKImage.FromPixelCopy(new SKImageInfo(width, height, SKColorType.Rgb888x), buffer);
```

Maybe this helps. For SkiaSharp you have to add the Alpha channel.

**Comment by Webreaper** [comment]
Thanks, that's useful. :)
