### ISSUE TITLE
Classification ?

### ISSUE THREAD

**Issue by NBarile** [NickSwardh/YoloDotNet#3]
Hi ! 

I just asking if this package can do image classification, and how ?

Thanks ^^

**Comment by NickSwardh** [comment]
Hi NBarlie, it only does object detection.

**Comment by NBarile** [comment]
Ok ... 

Thanks ^^

**Comment by NBarile** [comment]
> Just to let you know, classification has been added. Check the ReadMe for more info.

I see it yesterday !! 
Congratulation for this ;) 

I try it in my projet and it work really good.
