### ISSUE TITLE
Cant use GPU to infer

### ISSUE THREAD

**Issue by StefanCiobanu1989** [NickSwardh/YoloDotNet#35]
hi,i have a small issue. I have installed the versions of cuda and cudnn from the links from the readme and when i use :
 yolo = new Yolo(new YoloOptions
 {
     OnnxModel = Application.StartupPath + "model\\yolov11s.onnx",       
     ModelType = ModelType.ObjectDetection,                              
     Cuda = true,    <= this one breaks it                                                                             
     GpuId = 0,                                                          
     PrimeGpu = false,                                                  
 });

it dies with "Microsoft.ML.OnnxRuntime.OnnxRuntimeException: '[ErrorCode:RuntimeException] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1637 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "E:\Projects\Yoloader\Yoloader\bin\Debug\net8.0-windows\runtimes\win-x64\native\onnxruntime_providers_cuda.dll""

All paths are correct yet it does not work when trying to use the GPU. What am i doing wrong ?
![Capture](https://github.com/user-attachments/assets/333f6b28-be0e-4385-894f-26cb52289747)

**Comment by StefanCiobanu1989** [comment]
Fixed

**Comment by ibtehajali67** [comment]
> Fixed, misplaced some files

which files did you change
