### ISSUE TITLE
Is that proccible to make custom model for object detection 

### ISSUE THREAD

**Issue by TuniDev-HUB** [NickSwardh/YoloDotNet#41]

**Comment by NickSwardh** [comment]
Hi @TuniDev-HUB , yes, absolutely :)

1. Gather lots of pictures with the objects you want to detect.
2. Use any Yolo-compatible annotation tool out there to draw boxes around the objects. Personally I use [Label Studio](https://labelstud.io/)
4. Set Up Yolo from Ultralytics (https://docs.ultralytics.com/quickstart/)
5. Train the Model
6. Export to ONNX (https://docs.ultralytics.com/modes/export/#why-choose-yolo11s-export-mode)
